export const famousQuotes = [
    { author: "Steve Jobs", quote: "The only way to do great work is to love what you do." },
    { author: "Winston Churchill", quote: "Success is not final, failure is not fatal: it is the courage to continue that counts." },
    { author: "Albert Einstein", quote: "In the middle of every difficulty lies opportunity." },
    { author: "Theodore Roosevelt", quote: "Do what you can, with what you have, where you are." },
    { author: "Nelson Mandela", quote: "It always seems impossible until it’s done." },
    { author: "Mahatma Gandhi", quote: "You must be the change you wish to see in the world." },
    { author: "Sun Tzu", quote: "Opportunities multiply as they are seized." },
    { author: "John Lennon", quote: "Life is what happens when you're busy making other plans." },
    { author: "Booker T. Washington", quote: "If you want to lift yourself up, lift up someone else." },
    { author: "Sam Levenson", quote: "Don’t watch the clock; do what it does. Keep going." },
    { author: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop." },
    { author: "Henry Ford", quote: "Whether you think you can, or you think you can't – you're right." },
    { author: "Mark Twain", quote: "The secret of getting ahead is getting started." },
    { author: "Eleanor Roosevelt", quote: "The future belongs to those who believe in the beauty of their dreams." },
    { author: "Aristotle", quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit." },
    { author: "Thomas Edison", quote: "Genius is one percent inspiration and ninety-nine percent perspiration." },
    { author: "Benjamin Franklin", quote: "Tell me and I forget, teach me and I may remember, involve me and I learn." },
    { author: "Tony Robbins", quote: "The only limit to your impact is your imagination and commitment." },
    { author: "Maya Angelou", quote: "If you don’t like something, change it. If you can’t change it, change your attitude." },
    { author: "Oprah Winfrey", quote: "Turn your wounds into wisdom." },
    { author: "Franklin D. Roosevelt", quote: "The only thing we have to fear is fear itself." },
    { author: "Leonardo da Vinci", quote: "Learning never exhausts the mind." },
    { author: "Bruce Lee", quote: "Be like water, my friend." },
    { author: "Plato", quote: "The beginning is the most important part of the work." },
    { author: "Socrates", quote: "An unexamined life is not worth living." },
    { author: "Vincent Van Gogh", quote: "What would life be if we had no courage to attempt anything?" },
    { author: "Henry David Thoreau", quote: "Go confidently in the direction of your dreams. Live the life you have imagined." },
    { author: "Ralph Waldo Emerson", quote: "Do not go where the path may lead, go instead where there is no path and leave a trail." },
    { author: "Julius Caesar", quote: "Experience is the teacher of all things." },
    { author: "Lao Tzu", quote: "A journey of a thousand miles begins with a single step." },
    { author: "Marcus Aurelius", quote: "You have power over your mind – not outside events. Realize this, and you will find strength." },
    { author: "Dale Carnegie", quote: "Success is getting what you want. Happiness is wanting what you get." },
    { author: "Jim Rohn", quote: "Discipline is the bridge between goals and accomplishment." },
    { author: "Wayne Gretzky", quote: "You miss 100% of the shots you don’t take." },
    { author: "Michael Jordan", quote: "I've failed over and over and over again in my life. And that is why I succeed." },
    { author: "Babe Ruth", quote: "It’s hard to beat a person who never gives up." },
    { author: "C.S. Lewis", quote: "You are never too old to set another goal or to dream a new dream." },
    { author: "J.K. Rowling", quote: "It is our choices that show what we truly are, far more than our abilities." },
    { author: "Isaac Newton", quote: "If I have seen further, it is by standing on the shoulders of giants." },
    { author: "Helen Keller", quote: "Alone we can do so little; together we can do so much." },
    { author: "Florence Nightingale", quote: "I attribute my success to this: I never gave or took any excuse." },
    { author: "Harriet Tubman", quote: "Every great dream begins with a dreamer." },
    { author: "Marie Curie", quote: "Nothing in life is to be feared, it is only to be understood." },
    { author: "Walt Disney", quote: "All our dreams can come true, if we have the courage to pursue them." },
    { author: "Norman Vincent Peale", quote: "Change your thoughts and you change your world." },
    { author: "Robert Frost", quote: "Two roads diverged in a wood, and I – I took the one less traveled by, and that has made all the difference." },
    { author: "Pablo Picasso", quote: "Everything you can imagine is real." },
    { author: "Ernest Hemingway", quote: "Courage is grace under pressure." },
    { author: "Zig Ziglar", quote: "Your attitude, not your aptitude, will determine your altitude." }
  ];